djbooks/urls.py
from django.urls import path
from djbooks import views
from djbooks.views import Link, NewAuthor, EditAuthor, ProfileView
from django.urls import include

urlpatterns = [
    path("", views.home, name="home"),
    path("publisher/<pub_id>", views.publisher, name="publisher"),
    path("book/<book_id>", views.book, name='book'),
    path("books", views.book_list, name='books'),
    path("authors", NewAuthor.as_view(), name='authors'),
    path("new-publisher", views.get_publisher, name='new-publisher'),
    path("new-author", views.get_author, name='new-author'),
    path("links", Link.as_view(), name='links'),
    path ("new-author/<author_id>", EditAuthor.as_view(), name="edauthor"),
    path("new-author/<author_id>/delete", views.delete_author, name="deleteauthor"),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/profile/', ProfileView.as_view(), name='profile')
]

web_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path("", include("djbooks.urls")),
    path('admin/', admin.site.urls)
]

urlpatterns += staticfiles_urlpatterns()

djbooks/models.py
from django.db import models
from datetime import date


class Publisher(models.Model):
    name = models.CharField(max_length=30)
    address = models.CharField(max_length=50)
    city = models.CharField(max_length=60)
    country = models.CharField(max_length=50)
    website = models.URLField()

    class Meta:
        ordering = ["name"]

    def __str__(self):
        return self.name


class Author(models.Model):
    salutation = models.CharField(max_length=10)
    name = models.CharField(max_length=200)
    email = models.EmailField()

    def __str__(self):
        return self.name


class Book(models.Model):
    title = models.CharField(max_length=100)
    authors = models.ManyToManyField('Author')
    publisher = models.ForeignKey(Publisher, on_delete=models.CASCADE)
    publication_date = models.DateField(default=date(1900, 1, 1))

    def __str__(self):
        return self.title

class UsersLink(models.Model):
    url = models.URLField(max_length=200, default='http//:')

djbooks/forms.py
from msilib.schema import Class
from django import forms
from django.forms import ModelForm
from djbooks.models import Author, UsersLink
from django.contrib.auth.models import User

class PublisherForm(forms.Form):
    name = forms.CharField(label='Publisher name', max_length=30)
    address = forms.CharField(label='Publisher address', max_length=50)
    city = forms.CharField(label='Publisher city', max_length=60)
    country = forms.CharField(label='Publisher country', max_length=50)
    website = forms.URLField(label='Publisher website', max_length=100)


class AuthorForm(ModelForm):
    class Meta:
        model = Author
        fields = ['salutation', 'name', 'email']

class UsersLinkForm(ModelForm):
    class Meta:
        model = UsersLink
        fields = ['url']

class Userform(ModelForm):
    class Meta:
        model = User
        fields = ['username', 'email', 'date_joined']

djbooks/views.py
from doctest import SKIP
from faulthandler import disable
from http.client import HTTPResponse
from tkinter import DISABLED
from unicodedata import name
from unittest import result, skip
from urllib import request
from django.shortcuts import render, redirect
from django.http import HttpResponse
from .models import Author, Book, Publisher, UsersLink
from django.http import HttpResponseRedirect
from .forms import PublisherForm, AuthorForm, UsersLinkForm, Userform
from django.urls import is_valid_path, reverse
from django.views import View
from django.contrib.auth.models import User

def home(request):
    publisher_queryset = Publisher.objects.all()
    if 'msg' in request.session.keys():
        msg = request.session['msg']
        request.session['msg'] = ''
    else:
        msg = ''
    return render(request, 'djbooks/home.html', {'publisher_queryset': publisher_queryset, 'msg': msg})


def publisher(request, pub_id):
    pub_inf = Publisher.objects.get(id=pub_id)
    return render(request, 'djbooks/publisher.html', {'pub_inf': pub_inf})


def book(request, book_id):
    book_queryset = Book.objects.get(id=book_id)
    return render(request, 'djbooks/book.html', {'book_query': book_queryset})


def book_list(request):
    book_queryset = Book.objects.order_by('title')
    return render(request, 'djbooks/books.html', {'book_queryset': book_queryset})





def get_publisher(request):
    if request.method == 'POST':
        form = PublisherForm(request.POST)
        if form.is_valid():
            publisher = Publisher(name=form.cleaned_data['name'], address=form.cleaned_data['address'], city=form.cleaned_data['city'],
                                  country=form.cleaned_data['country'], website=form.cleaned_data['website'])  # тут ошибка была - не cleaned_data.name, а cleaned_data['name']
            publisher.save()
            request.session['msg'] = f"New publisher {form.cleaned_data['name']} has been added. Congratulations!"
            return redirect("home")
    else:
        form = PublisherForm()

    # тут ошибка - в адресе не было djbooks/
    return render(request, 'djbooks/addpublisher.html', {'form': form})


def get_author(request):
    if request.method == 'POST':
        form = AuthorForm(request.POST)
        if form.is_valid():
            form.save()
            request.session['msg'] = f"New author {form.cleaned_data['salutation']} {form.cleaned_data['name']} has been added."
            return redirect('authors')
    else:
        form = AuthorForm()

    return render(request, 'djbooks/addauthor.html', {'form': form})

class Link(View):
    template_name = 'djbooks/links.html'
    initial = {'url': 'http://'}
    form_class = UsersLinkForm
    
    

    def get(self, request, *args, **kwargs):
        form = self.form_class()
        links_queryset = UsersLink.objects.all()
        return render(request, self.template_name, {'form': form,'links_queryset': links_queryset})

    
    def post(self, request, *args, **kwargs):
        form = self.form_class(request.POST)
        if form.is_valid():
            form.save()
            return redirect('links')
        else:
            form = self.form_class()
        return render(request, self.template_name, {'form': form})


class NewAuthor(View):
    template_name = 'djbooks/authors.html'
    initial = {'key': 'value'}
    form_class = AuthorForm
    
    
    def get(self, request, *args, **kwargs ):
        form = self.form_class()
        authors_queryset = Author.objects.order_by('name')
        if 'msg' in request.session.keys():
            msg = request.session['msg']
            request.session['msg'] = ''
        else:
            msg = ''
        return render(request, self.template_name, {'authors_queryset': authors_queryset, 'msg': msg, 'form': form})

    def post(self, request, *args, **kwargs ):
        form= self.form_class(request.POST)
        if form.is_valid():
            form.save()
            return redirect('authors')
        return render(request, self.template_name, {'form': form} )


class EditAuthor(View):
    template_name ="djbooks/editauthor.html"
    form_class = AuthorForm

    def get(self, request, author_id, *args, **kwargs):
        author = Author.objects.get(pk=author_id)
        f = self.form_class(instance=author)

        return render(request, self.template_name, {"f": f})
        
    def post(self, request, author_id,  *args, **kwargs):
        f = self.form_class(request.POST, instance=Author.objects.get(pk=author_id))
        if f.is_valid():
            f.save()
            return redirect('authors')
        return render(request, self.template_name, {"f":f})

def delete_author(request, author_id):
    Author.objects.get(pk=author_id).delete()
    return redirect('authors')


class ProfileView(View):
    template_name="djbooks/profile.html"
    form_class = Userform
    def get(self,  request,*args, **kwargs):
        user = User.objects.get(username=request.user.username)
        f=self.form_class(instance=user) 
        return render(request, self.template_name, {"user":user,"f":f})

    def post(self, request,*args, **kwargs):
        pass
    

djbooks/templates/djbooks/addauthor.html
{% extends "djbooks/layout.html" %}
{% block title %}
Add Author
{% endblock %}

{% block content %}
<form method="post" novalidate>
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Submit">
</form>
{% endblock %}

djbooks/templates/djbooks/addpublisher.html
{% extends "djbooks/layout.html" %}
{% block title %}
Add Publisher
{% endblock %}

{% block content %}
<form method="post" novalidate>
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Submit">
</form>
{% endblock %}

djbooks/templates/djbooks/admin/base_site.html
{% extends "admin/base.html" %}

{% block title %}{% if subtitle %}{{ subtitle }} | {% endif %}{{ title }} | {{ site_title|default:_('Admin page') }}{% endblock %}

{% block branding %}
<h1 id="site-name"><a href="{% url 'admin:index' %}">{{ site_header|default:_('Django administration') }}</a></h1>
{% endblock %}

{% block nav-global %}{% endblock %}

djbooks/templates/djbooks/authors.html
{% extends "djbooks/layout.html" %}
{% block title%}
    Authorlist
{% endblock %}

{% block content %}
<div style="text-align:center;padding:15px">
<h2>Author list</h2>
</div>
<div class="w3-container w3-center">
    {% if msg %}
    <div class="w3-panel w3-pale-green w3-display-container" id='message'>
        <span onclick="this.parentElement.style.display='none'"
            class="w3-button w3-large w3-display-topright">&times;</span>
        <h3>Success!</h3>
        <p>{{ msg }}</p>
    </div>
    <script>
        setTimeout(function () { document.getElementById('message').style.display = 'none'; }, 3000);
    </script>
    {% endif %}

<div style="padding:1px">
<div class = 'container'>
    <table class='table table-hover table-bordered'>
        <tr>
        <th>Name</th>
        <th>Salutation</th>
        <th>Email</th>
        <th>Edit</th>
        <th>Delete</td>
        </tr>

        {% for ath in authors_queryset %}
            <tr>
                <td>{{ ath.name }}</td>
                <td>{{ ath.salutation }}</td>
                <td>{{ ath.email }}</td>
                <td>
                  <a href= "{% url 'edauthor' ath.id %}">
                    <span>Edit</span></a>
                  </td> 
                  <td>
                  <a href= "{% url 'deleteauthor' ath.id %}">
                    <span>delete</span></a> 
                </td>
            </tr>
        {%endfor%}
    </table>
</div>
</div>



<div style="padding:30px;text-align:center" >
<button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#myModal">
    Add author
  </button>
</div>



  <div class="modal" id="myModal" style='text-align:center'>
    <div class="modal-dialog modal-lg">
      <div class="modal-content">
        
        <!-- Modal Header -->
        <div class="modal-header">
          <h4 class="modal-title">Add Author</h4>
          <button type="button" class="btn-close" data-bs-dismiss="modal"></button>
        </div>
  
        <!-- Modal body -->
          <div class="modal-body", style='text-align:center;padding:200px;font-size:30px'>
          <form method="post" novalidate>
            {% csrf_token %}
            {{ form.as_p }}
            <input type="submit" value="Submit">
        </form>
        </div>
      </div>
    </div>
  </div>



{% endblock %}




























































<!--
<div class = ' w3-container w3-center'>
    <ul class="w3-ul w3-border">

        {% for a in authors_queryset %}
        {% ifchanged a.name.0 %}
        <b><mark>
                <h2>{{ a.name.0}}</h2>
            </mark></b>
        {% for ath in authors_queryset %}
        {% if a.name.0 == ath.name.0 %}
        <li>
            <h3>{{ ath.name }}</h3>
        </li>
        {%endif%}
        {% endfor %}
        {% endifchanged %}
        {% endfor %}
    </ul>
</div>

-->

djbooks/templates/djbooks/book.html
{% extends "djbooks/layout.html" %}
{% block title %}
Book_inf
{% endblock %}

{% block content %}

<p><b>Book Title:</b> {{book_query.title}}</p>
<p><b>Publication date:</b> {{book_query.publication_date}}</p>

<h3><b>Publisher:</b></h3>
<p>{{book_query.publisher.name}}</p>

<h3><b>Authors:</b></h3>
{% for a in book_query.authors.all %}
<li>{{a.name}}</li>
{% endfor %}

{% endblock %}

djbooks/templates/djbooks/books.html
{% extends "djbooks/layout.html" %}
{% block title %}
Booklist
{% endblock %}

{% block content %}

<h2>Book list</h2>
<div class="w3-container w3-center">
    <ul class="w3-ul w3-border">
        {% for b in book_queryset %}
        {% ifchanged b.title.0 %}
        <h3><b> {{ b.title.0 }} </b></h3>
        {% for f in book_queryset %}
        {% if b.title.0 == f.title.0 %}
        <li>
            <h3> {{ f.title }}</h3>
        </li>
        {% endif %}
        {% endfor %}
        {% endifchanged %}
        {% endfor %}
    </ul>
</div>

{% endblock %}

djbooks/templates/djbooks/editauthor.html
{% extends "djbooks/layout.html" %}
{% block title %}
Edit Author
{% endblock %}

{% block content %}

<form method="post" novalidate>
    {% csrf_token %}
    {{ f.as_p }}
    <input type="submit" value="Submit">
</form>

{% endblock %}

djbooks/templates/djbooks/home.html
{% extends "djbooks/layout.html" %}
{% block title %}
Home
{% endblock %}

{% block content %}

<!--<img src = 'https://techcrunch.com/wp-content/uploads/2019/01/GettyImages-876317622.jpg' alt="W3Schools.com"  width="104"  height="142">  -->
<div class="w3-container">
    {% if msg %}
    <div class="w3-panel w3-pale-green w3-display-container">
        <span onclick="this.parentElement.style.display='none'"
            class="w3-button w3-large w3-display-topright">&times;</span>
        <h3>Success!</h3>
        <p>{{ msg }}</p>
    </div>
    {% endif %}
    <h2>Publishers</h2>
    <ul class="w3-ul w3-border w3-center">
        {% for publisher in publisher_queryset %}
        <li><a href="{% url 'publisher' publisher.id %}">
                <h3>Издатель {{ publisher.name }}</h3>
            </a></li>
        {% endfor %}
    </ul>
</div>

{% endblock %}

djbooks/templates/djbooks/layout.html
{% load static %}
<!DOCTYPE html>
<html>

<head>
  
  <link href="https://fonts.googleapis.com/css2?family=Bebas+Neue&display=swap" rel="stylesheet">
    <meta charset="utf-8" />
    <title>{% block title %}{% endblock %}</title
    <link rel="icon" type="image/x-icon" href="{% static 'djbooks/favicon.ico' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
    <meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<body> 

 <div  style='padding-bottom:20px;font-family:Bebas+Neue;font-size:20px;' >
    <nav class="navbar navbar-expand-sm bg-dark navbar-dark justify-content-center">
        <div class="container-fluid">
          <!-- Links -->
          <ul class="navbar-nav">
            <li class="nav-item">
              <a class="nav-link active" href="{% url 'home' %}">Home</a>
            </li>
            <li class="nav-item">
              <a class="nav-link active" href="{% url 'books' %}">Books</a>
            </li>
            <li class="nav-item">
              <a class="nav-link active" href="{% url 'authors' %}">Authors</a>
            </li>
            <li class="nav-item">
                <a class="nav-link active" href="{% url 'new-publisher' %}">Add Publisher</a>
            </li>
              <li class="nav-item">
                <a class="nav-link active" href="{% url 'new-author' %}">Add Author</a>
              </li>
              <li class="nav-item">
                <a class="nav-link active" href="{% url 'links' %}">Links</a>
              </li>
                <li class="nav-item">
                  <a class="nav-link active" href="{% url 'login' %}">Login</a>
              </li>
          </ul>
        </div>
      </nav>
    </div>
  <div style='font-family:Bebas+Neue'>
    <div class="body-content">
        {% block content %}
        Django
        
        {% endblock %}

    </div>
  </div>
<script></script>
</body>
</div>

</html>

djbooks/templates/djbooks/links.html
{% extends "djbooks/layout.html" %}
{% block title %}
Add your link 
{% endblock %}
{% block content %}
Here you can add your link on authors, publisher, or books.

<form method="post" novalidate>
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Submit">
</form>


<ul>
{%for links in links_queryset%}
<li><a href="{{links.url}}">
    {{links.url}}
</a>
</li>
{%endfor%}
</ul>



{% endblock %}

djbooks/templates/djbooks/profile.html
{% extends "djbooks/layout.html" %}
{% block title %}
Profile
{% endblock %}

{% block content %}
<form disabled="True" method="get" novalidate>
    {% csrf_token %}
    {{ f.as_p }}
</form>
{% endblock %}

djbooks/templates/djbooks/publisher.html
{% extends "djbooks/layout.html" %}
{% block title %}
Information
{% endblock %}

{% block content %}

<h3>Имя - <i>{{pub_inf.name}}</i></h3>
<h3>Адрес - <i>{{pub_inf.address}}</i></h3>
<h3>Город - <i>{{pub_inf.city}}</i></h3>
<h3>Страна - <i>{{pub_inf.country}}</i></h3>
<h3>Вебсайт - <i>{{pub_inf.website}}</i></h3>
<div class="w3-container w3-center ">
    <ul class="w3-ul w3-border ">
        {% for book in pub_inf.book_set.all %}
        <li><a href="{% url 'book'  book.id %}">Книга <h3>{{book.title }}</h3></a></li>
        {% endfor %}
    </ul>

    {% endblock %}